config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart' 
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  devise_for :users
  devise_for :models
  root "storefront#all_items"
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :products
end

app/models/enter.rb
class Enter < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :order, optional: true
    belongs_to :product
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items
    belongs_to :user, optional: true
    serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :categories
    before_action :brands
    def categories
        @categories = Category.all
    end

    def brands
        @brands = Product.pluck(:brand).uniq
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
    line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])
    line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
    redirect_back(fallback_location: root_path)
  end

  def view_order
    @line_items = LineItem.all
  end

  def checkout
    line_items = LineItem.all
    @order = Order.create(user_id: current_user.id, subtotal: 0)


    line_items.each do |line_item|
      line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
      @order.subtotal += line_item.line_item_total
      @order.order_items[line_item.product_id] = line_item.quantity
    end
    @order.save

    @order.update(sales_tax: (@order.subtotal * 0.08))
    @order.update(grand_total: (@order.sales_tax + @order.subtotal))
    line_items.destroy_all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
    @products = Product.all
  end

  def items_category
    @category = Category.find(params[:category])
    @products = Product.where(category_id: params[:category_id])
  end

  def items_by_brand
    @brand = params[:brand]
    @products = Product.where(brand: params[:brand])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Thank You for your purchase</h1>
<p>Order ID: <%= @order.id %>
<p>Sales Tax: <%= @order.sales_tax %></p>
<p>Grand Total: <%= @order.grand_total %></p>

<% @order.order_items.each do |product_id, quantity| %>
   <p><%= Product.find(product_id).name %> -- <%= quantity %></p>
<% end %>

app/views/cart/view_order.html.erb
<h1>My Cart</h1>
<% @line_items.each do |line_item| %>
    <p><%= line_item.product.name %></p>
    <p>Quantity: <%= line_item.quantity %></p>
    <p>Product Price:<%= number_to_currency line_item.product.price %></p>
    <p>Subtotal:<%= number_to_currency line_item.line_item_total %></p>

<% end %>


<%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>s
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">
        <h1>Amazion</h1>
        <p>Welcome to the <span style="color: orange">Worldwide</span> Ecommerce <span style="color: orange">Market</span></p>
    </div>
      <div class="container">
        <nav class="navbar navbar-default">
      <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">STORE</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nac navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categpries</a>
            <ul class="dropdown-menu">
                <% @categories.each do |category| %>
                  <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
                <% end %>
            </ul>
        </li>
            <br>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands</a>
          <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
          </ul>
        </li>
      </ul>
  
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "View Cart", view_order_path %></li>
            <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
      </ul>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
          </li>
             <% else %>
             <li><%= link_to "Sign In", new_user_session_path %></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
            <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.collect{|c| [c.name, c.id]}, {include_blank: "Please select a category"} %>
  </div>

  <div class="field">
    <strong>Upload an Image Picture:</strong>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_product_list.html.erb
<div class="row">
    <% @products.each do |product| %>
        <div class="col-md-4">
            <div class="well">
                <% if product.image.url.blank? == false%>
                    <p><%= image_tag product.image.url %></p>   
                <% end %>

               <h3><%= link_to product.name, product %></h3>
               <p><%= number_to_currency product.price %></p>
               <p>
                    <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
                        <span class="glyphicon glyphicon-plus"></span>
                    </a>
               </p>
            </div>
        </div>
         <div class="modal fade" id="myModal_<%= product.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
        </div>
        <div class="modal-body">
            <%= product.description%>
            <%= product.price %>
            <%= product.brand %>
        </div>

        </div>
        <div class='model-footer'>
            <%= form_tag add_to_cart_path do %>
                <%= hidden_field_tag :product_id, product.id %>
                <%= number_field_tag :quantity, nil, placeholder: "How many?" %>
                <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
    </div>
 <% end %>
  
</div>

app/views/storefront/all_items.html.erb
<div class="title-container">
<h1>Welcome To Main Market</h1>
</div>

<%= render 'product_list'%>

app/views/storefront/items_by_brand.html.erb
<h1>All items of the <%= @brand %> brand</h1>

<%= render 'product_list' %>

app/views/storefront/items_category.html.erb
<h1>All of the products in category <%= @category.name %></h1>

<%= render 'product_list' %>